### ISSUE TITLE
Installation fails related to depency on inherits

### ISSUE THREAD

**Issue by chrisdamato** [uschek/somafm#2]
sudo npm install --global somafm

```
...
npm` http 200 https://registry.npmjs.org/spdx-license-ids
npm http GET https://registry.npmjs.org/is-utf8
npm http 304 https://registry.npmjs.org/is-utf8
/bin/somafm -> /lib/node_modules/somafm/cli.js
npm WARN unmet dependency /lib/node_modules/block-stream requires inherits@'~2.0.0' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /lib/node_modules/fstream requires inherits@'~2.0.0' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /lib/node_modules/fstream-ignore requires inherits@'2' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /lib/node_modules/fstream-npm requires inherits@'2' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /lib/node_modules/glob requires inherits@'2' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /lib/node_modules/npmconf requires inherits@'~2.0.0' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /lib/node_modules/tar requires inherits@'2' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
somafm@1.2.0 /lib/node_modules/somafm
├── term-title@1.0.0
├── object-assign@4.1.0
├── trim@0.0.1
├── minimist@1.2.0
├── isbin@0.0.2 (async@0.1.22)
├── chalk@1.1.3 (escape-string-regexp@1.0.5, supports-color@2.0.0, ansi-styles@2.2.1, has-ansi@2.0.0, strip-ansi@3.0.1)
├── cli-truncate@0.2.1 (slice-ansi@0.0.4, string-width@1.0.2)
├── copy-paste@1.3.0 (sync-exec@0.6.2, iconv-lite@0.4.13)
├── got@5.6.0 (is-redirect@1.0.0, lowercase-keys@1.0.0, is-stream@1.1.0, is-plain-obj@1.1.0, unzip-response@1.0.1, timed-out@2.0.0, is-retry-allowed@1.1.0, node-status-codes@1.0.0, read-all-stream@3.1.0, duplexer2@0.1.4, url-parse-lax@1.0.0, create-error-class@3.0.2, pinkie-promise@2.0.1, parse-json@2.2.0, readable-stream@2.1.5)
└── dateformat@1.0.12 (get-stdin@4.0.1, meow@3.7.0)

```

**Comment by MatthewVita** [comment]
Works for me on NPM v3.10.3 ... what version are you on?

**Comment by uschek** [comment]
@chrisdamato Looks like these are warnings for other packages you have installed on your system. I tried installing with npm v2.14.3 and got similar results for packages installed on my system. According to the logs the package was still installed successfully.

Anyway, I recommend using the latest version of Node and npm.

**Comment by chrisdamato** [comment]
Thanks for your help, I am new at this and thought I might be missing something easy. I am using the latest versions from the Fedora 23 distro but will check and confirm.

**Comment by chrisdamato** [comment]
I updated npm to 3.10.8 and the installation was successful but I still can't get the program to run. Tried a number of uninstall/reinstall/update commands but no luck so far.

If I am having a node/npm problem related to my cluelessness feel free to close the issue, but I will share this in case it's a problem you might care about.

```
$ somafm

/usr/lib/node_modules/somafm/cli.js:24
  `
  ^
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3

```

**Comment by uschek** [comment]
You need at least Node.js v4.0.0 to use this module. (The installer should have given you a warning.)

For Node version management, I recommend [`n`](https://github.com/tj/n) or [nvm](https://github.com/creationix/nvm). On my systems, I use this one-liner to install `n` locally to `~/local/node`:

```sh
curl -L http://git.io/n-install | N_PREFIX=$HOME/local/node bash -s -- -y
```

Then, to install the latest version of Node, run:

```sh
n latest
```

and finally upgrade npm:

```sh
npm install --global npm
```

I hope that helps.

**Comment by chrisdamato** [comment]
Hey thanks very much, that did the trick! I had no idea the distro version of node could be so far behind.

Much appreciate your tip about nvm and your one-liner. Now on to enjoying this tool for my favorite radio station!
